server:
  port: 9080
spring:
  datasource:
#    url: jdbc:mysql://192.168.3.32:3306/volvo_invoice?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
#    url: jdbc:mysql://101.35.52.237:3308/volvo_invoice?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    url: jdbc:mysql://49.51.72.242:3306/rl_bCard?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: rl.ai.1L
#    password: Root.123
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  swagger3:
    description: bCard项目
    title: bCard项目
    name: swagger3
    email: bCard项目@qq.com
    version: 1.1

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    refresh-mapper: true
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  ##mybatis设置
  mapper-locations: classpath:mapper/**/*.xml  #mapper.xml文件所

bCard-path-win: D:\bCard\png\
bCard-path-linux: /rl-ai/bCard-Jar/png/
